state_details = {
    "Andhra Pradesh": {"short_name": "AP", "state_code": "28"},
    "Arunachal Pradesh": {"short_name": "AR", "state_code": "12"},
    "Assam": {"short_name": "AS", "state_code": "18"},
    "Bihar": {"short_name": "BR", "state_code": "10"},
    "Chattisgarh": {"short_name": "CG", "state_code": "22"},
    "Goa": {"short_name": "GA", "state_code": "30"},
    "Gujarat": {"short_name": "GJ", "state_code": "24"},
    "Haryana": {"short_name": "HR", "state_code": "06"},
    "Himachal Pradesh": {"short_name": "HP", "state_code": "02"},
    "Jharkhand": {"short_name": "JH", "state_code": "20"},
    "Karnataka": {"short_name": "KA", "state_code": "29"},
    "Kerala": {"short_name": "KL", "state_code": "32"},
    "Madhya Pradesh": {"short_name": "MP", "state_code": "23"},
    "Maharashtra": {"short_name": "MH", "state_code": "27"},
    "Manipur": {"short_name": "MN", "state_code": "14"},
    "Meghalaya": {"short_name": "ML", "state_code": "17"},
    "Mizoram": {"short_name": "MZ", "state_code": "15"},
    "Nagaland": {"short_name": "NL", "state_code": "13"},
    "Odisha": {"short_name": "OR", "state_code": "21"},
    "Punjab": {"short_name": "PB", "state_code": "03"},
    "Rajasthan": {"short_name": "RJ", "state_code": "08"},
    "Sikkim": {"short_name": "SK", "state_code": "11"},
    "Tamil Nadu": {"short_name": "TN", "state_code": "33"},
    "Telangana": {"short_name": "TG", "state_code": "36"},
    "Tripura": {"short_name": "TR", "state_code": "16"},
    "Uttar Pradesh": {"short_name": "UP", "state_code": "09"},
    "Uttarakhand": {"short_name": "UT", "state_code": "05"},
    "West Bengal": {"short_name": "WB", "state_code": "19"},
    "Andaman and Nicobar Islands": {"short_name": "AN", "state_code": "35"},
    "Chandigarh": {"short_name": "CH", "state_code": "04"},
    "Dadra and Nagar Haveli and Daman and Diu": {"short_name": "DN", "state_code": "26"},
    "Lakshadweep": {"short_name": "LD", "state_code": "31"},
    "Delhi": {"short_name": "DL", "state_code": "07"},
    "Puducherry": {"short_name": "PY", "state_code": "34"},
    "Ladakh": {"short_name": "LA", "state_code": "37"},
    "Jammu & Kashmir": {"short_name": "JK", "state_code": "01"}
}

state_short_name_details={
    "AP": {"state_name": "Andhra Pradesh", "state_code": "28"},
    "AR": {"state_name": "Arunachal Pradesh", "state_code": "12"},
    "AS": {"state_name": "Assam", "state_code": "18"},
    "BR": {"state_name": "Bihar", "state_code": "10"},
    "CG": {"state_name": "Chattisgarh", "state_code": "22"},
    "CT": {"state_name": "Chattisgarh", "state_code": "22"},
    "GA": {"state_name": "Goa", "state_code": "30"},
    "GJ": {"state_name": "Gujarat", "state_code": "24"},
    "HR": {"state_name": "Haryana", "state_code": "06"},
    "HP": {"state_name": "Himachal Pradesh", "state_code": "02"},
    "JH": {"state_name": "Jharkhand", "state_code": "20"},
    "KA": {"state_name": "Karnataka", "state_code": "29"},
    "KL": {"state_name": "Kerala", "state_code": "32"},
    "MP": {"state_name": "Madhya Pradesh", "state_code": "23"},
    "MH": {"state_name": "Maharashtra", "state_code": "27"},
    "MN": {"state_name": "Manipur", "state_code": "14"},
    "ML": {"state_name": "Meghalaya", "state_code": "17"},
    "MZ": {"state_name": "Mizoram", "state_code": "15"},
    "NL": {"state_name": "Nagaland", "state_code": "13"},
    "OR": {"state_name": "Odisha", "state_code": "21"},
    "PB": {"state_name": "Punjab", "state_code": "03"},
    "RJ": {"state_name": "Rajasthan", "state_code": "08"},
    "SK": {"state_name": "Sikkim", "state_code": "11"},
    "TN": {"state_name": "Tamil Nadu", "state_code": "33"},
    "TG": {"state_name": "Telangana", "state_code": "36"},
    "TR": {"state_name": "Tripura", "state_code": "16"},
    "UP": {"state_name": "Uttar Pradesh", "state_code": "09"},
    "UT": {"state_name": "Uttarakhand", "state_code": "05"},
    "UK": {"state_name": "Uttarakhand", "state_code": "05"},
    "WB": {"state_name": "West Bengal", "state_code": "19"},
    "AN": {"state_name": "Andaman and Nicobar Islands", "state_code": "35"},
    "CH": {"state_name": "Chandigarh", "state_code": "04"},
    "DN": {"state_name": "Dadra and Nagar Haveli and Daman and Diu", "state_code": "26"},
    "LD": {"state_name": "Lakshadweep", "state_code": "31"},
    "DL": {"state_name": "Delhi", "state_code": "07"},
    "PY": {"state_name": "Puducherry", "state_code": "34"},
    "LA": {"state_name": "Ladakh", "state_code": "37"},
    "JK": {"state_name": "Jammu & Kashmir", "state_code": "01"}
}

state_code_details={
    "28": {"state_name": "Andhra Pradesh", "short_name": "AP"},
    "12": {"state_name": "Arunachal Pradesh", "short_name": "AR"},
    "18": {"state_name": "Assam", "short_name": "AS"},
    "10": {"state_name": "Bihar", "short_name": "BR"},
    "22": {"state_name": "Chattisgarh", "short_name": "CG"},
    "30": {"state_name": "Goa", "short_name": "GA"},
    "24": {"state_name": "Gujarat", "short_name": "GJ"},
    "06": {"state_name": "Haryana", "short_name": "HR"},
    "02": {"state_name": "Himachal Pradesh", "short_name": "HP"},
    "20": {"state_name": "Jharkhand", "short_name": "JH"},
    "29": {"state_name": "Karnataka", "short_name": "KA"},
    "32": {"state_name": "Kerala", "short_name": "KL"},
    "23": {"state_name": "Madhya Pradesh", "short_name": "MP"},
    "27": {"state_name": "Maharashtra", "short_name": "MH"},
    "14": {"state_name": "Manipur", "short_name": "MN"},
    "17": {"state_name": "Meghalaya", "short_name": "ML"},
    "15": {"state_name": "Mizoram", "short_name": "MZ"},
    "13": {"state_name": "Nagaland", "short_name": "NL"},
    "21": {"state_name": "Odisha", "short_name": "OR"},
    "03": {"state_name": "Punjab", "short_name": "PB"},
    "08": {"state_name": "Rajasthan", "short_name": "RJ"},
    "11": {"state_name": "Sikkim", "short_name": "SK"},
    "33": {"state_name": "Tamil Nadu", "short_name": "TN"},
    "36": {"state_name": "Telangana", "short_name": "TG"},
    "16": {"state_name": "Tripura", "short_name": "TR"},
    "09": {"state_name": "Uttar Pradesh", "short_name": "UP"},
    "05": {"state_name": "Uttarakhand", "short_name": "UT"},
    "19": {"state_name": "West Bengal", "short_name": "WB"},
    "35": {"state_name": "Andaman and Nicobar Islands", "short_name": "AN"},
    "04": {"state_name": "Chandigarh", "short_name": "CH"},
    "26": {"state_name": "Dadra and Nagar Haveli and Daman and Diu", "short_name": "DN"},
    "31": {"state_name": "Lakshadweep", "short_name": "LD"},
    "07": {"state_name": "Delhi", "short_name": "DL"},
    "34": {"state_name": "Puducherry", "short_name": "PY"},
    "37": {"state_name": "Ladakh", "short_name": "LA"},
    "01": {"state_name": "Jammu & Kashmir", "short_name": "JK"}
}