state_details = {
    "Andhra Pradesh": {"short_name": "AP", "state_code": "28"},
    "Arunachal Pradesh": {"short_name": "AR", "state_code": "12"},
    "Assam": {"short_name": "AS", "state_code": "18"},
    "Bihar": {"short_name": "BR", "state_code": "10"},
    "Chattisgarh": {"short_name": "CG", "state_code": "22"},
    "Goa": {"short_name": "GA", "state_code": "30"},
    "Gujarat": {"short_name": "GJ", "state_code": "24"},
    "Haryana": {"short_name": "HR", "state_code": "06"},
    "Himachal Pradesh": {"short_name": "HP", "state_code": "02"},
    "Jharkhand": {"short_name": "JH", "state_code": "20"},
    "Karnataka": {"short_name": "KA", "state_code": "29"},
    "Kerala": {"short_name": "KL", "state_code": "32"},
    "Madhya Pradesh": {"short_name": "MP", "state_code": "23"},
    "Maharashtra": {"short_name": "MH", "state_code": "27"},
    "Manipur": {"short_name": "MN", "state_code": "14"},
    "Meghalaya": {"short_name": "ML", "state_code": "17"},
    "Mizoram": {"short_name": "MZ", "state_code": "15"},
    "Nagaland": {"short_name": "NL", "state_code": "13"},
    "Odisha": {"short_name": "OR", "state_code": "21"},
    "Punjab": {"short_name": "PB", "state_code": "03"},
    "Rajasthan": {"short_name": "RJ", "state_code": "08"},
    "Sikkim": {"short_name": "SK", "state_code": "11"},
    "Tamil Nadu": {"short_name": "TN", "state_code": "33"},
    "Telangana": {"short_name": "TG", "state_code": "36"},
    "Tripura": {"short_name": "TR", "state_code": "16"},
    "Uttar Pradesh": {"short_name": "UP", "state_code": "09"},
    "Uttarakhand": {"short_name": "UK", "state_code": "05"},
    "West Bengal": {"short_name": "WB", "state_code": "19"},
    "Andaman and Nicobar Islands": {"short_name": "AN", "state_code": "35"},
    "Chandigarh": {"short_name": "CH", "state_code": "04"},
    "Dadra and Nagar Haveli and Daman and Diu": {"short_name": "DN", "state_code": "26"},
    "Lakshadweep": {"short_name": "LD", "state_code": "31"},
    "Delhi": {"short_name": "DL", "state_code": "07"},
    "Puducherry": {"short_name": "PY", "state_code": "34"},
    "Ladakh": {"short_name": "LA", "state_code": "37"},
    "Jammu & Kashmir": {"short_name": "JK", "state_code": "01"}
}